[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "LSPScript"
requires-python = ">=3.8"
authors = [
    { name = "Delphy", email = "delphi1024@gmail.com" }
]
dynamic = ["version"]

[tool.pytest.ini_options]
testpaths = [
    "."
]
