[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lspscript"
requires-python = ">=3.8"
authors = [
    { name = "Delphy", email = "delphi1024@gmail.com" }
]
dynamic = ["version"]

[tool.setuptools.packages.find]
include = ["lspscript*"]

[tool.pytest.ini_options]
testpaths = [
    "."
]
asyncio_mode = "auto"
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]
