name: Test Generator

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version to use
        required: true
        type: string
      runner:
        description: Target runner (e.g. "ubuntu-latest")
        required: true
        type: string

jobs:
  test-gen:
    runs-on: ${{ inputs.runner }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: python -m pytest gen/test
